/**
 * Generates supabase/migrations/20261002000300_seed_reference_data.sql from the
 * reference values in src/lib/payroll/defaults.ts, so the SQL and the tested
 * values can never drift apart.   Run: npx tsx scripts/generate-seed.ts
 */
import { writeFileSync } from "node:fs";
import { BIR_2023, PAGIBIG_2024, PAY_RATES_DOLE, PHILHEALTH_2024, SSS_2025 } from "../src/lib/payroll/defaults";

const q = (s: string | null | undefined) => (s == null ? "null" : `'${s.replace(/'/g, "''")}'`);
const j = (o: unknown) => `${q(JSON.stringify(o))}::jsonb`;

const configs = [
  { kind: "sss", name: "SSS contribution schedule 2025 (15%)", cfg: SSS_2025, notes: "MSC ₱5,000–₱35,000; MSC above ₱20,000 goes to the Mandatory Provident Fund (WISP). EC ₱10 below ₱15,000 MSC, ₱30 at ₱15,000 and up. Confirmed unchanged for 2026." },
  { kind: "philhealth", name: "PhilHealth premium 5% (2024 onward)", cfg: PHILHEALTH_2024, notes: "Monthly basic salary basis; shared equally by employer and employee." },
  { kind: "pagibig", name: "Pag-IBIG / HDMF — MFS ₱10,000", cfg: PAGIBIG_2024, notes: "Employee 1% if monthly compensation ≤ ₱1,500, else 2%; employer 2%." },
  { kind: "bir", name: "BIR withholding tax table 2023 onward", cfg: BIR_2023, notes: "Daily, weekly, semi-monthly, monthly and annual tables; ₱90,000 13th month & other benefits exemption." },
  { kind: "pay_rates", name: "DOLE premium & overtime multipliers", cfg: PAY_RATES_DOLE, notes: "Multipliers of the basic hourly rate. NSD = 10% of the applicable hourly rate (10 PM – 6 AM)." },
];

const sql: string[] = [
  "-- GENERATED by scripts/generate-seed.ts — do not edit by hand.",
  "-- Reference data. Verify every row against the latest official issuance before processing payroll.",
  "",
  "insert into statutory_configurations (kind, name, effective_from, status, payload, source, notes) values",
  configs
    .map(({ kind, name, cfg, notes }) => {
      const { source, effectiveFrom, configId: _c, ...payload } = cfg as typeof cfg & { configId?: string };
      return `  (${q(kind)}, ${q(name)}, ${q(effectiveFrom)}, 'active', ${j(payload)}, ${q(source!)}, ${q(notes)})`;
    })
    .join(",\n") + ";",
  "",
];

const earningTypes: [string, string, string, string, boolean, boolean, boolean, string][] = [
  // code, label, category, tax_treatment, in_sss, in_pagibig, in_13th, note
  ["ALLOW_TRANSPO", "Transportation allowance", "allowance", "taxable", true, false, false, "Taxable unless it is a liquidated reimbursement of business expense."],
  ["ALLOW_MEAL", "Meal allowance", "allowance", "taxable", true, false, false, "Taxable. OT meal allowance within the de minimis limit uses MEAL_OT."],
  ["MEAL_OT", "Overtime meal allowance", "allowance", "de_minimis", false, false, false, "De minimis only within the BIR limit; encode any excess as taxable."],
  ["RICE", "Rice subsidy", "allowance", "de_minimis", false, false, false, "De minimis only within the BIR limit; encode any excess as taxable."],
  ["ALLOW_COMM", "Communication allowance", "allowance", "taxable", true, false, false, "Taxable unless liquidated."],
  ["ALLOW_MOBILE", "Mobile allowance", "allowance", "taxable", true, false, false, "Taxable unless liquidated."],
  ["ALLOW_FUEL", "Fuel allowance", "allowance", "taxable", true, false, false, "Taxable unless liquidated."],
  ["ALLOW_HOUSING", "Housing allowance", "allowance", "taxable", true, false, false, "Review fringe-benefit rules for managerial staff."],
  ["ALLOW_OTHER", "Other allowance", "allowance", "taxable", true, false, false, ""],
  ["COMMISSION", "Sales commission", "commission", "taxable", true, false, false, "Supplementary compensation."],
  ["INCENTIVE", "Incentive", "incentive", "taxable", true, false, false, "Productivity/sales incentive."],
  ["BONUS", "Bonus", "bonus", "other_benefit", false, false, false, "Counts toward the ₱90,000 13th month & other benefits exemption."],
  ["THIRTEENTH", "13th month pay", "bonus", "other_benefit", false, false, false, "Counts toward the ₱90,000 exemption."],
  ["LEAVE_CONV", "Leave conversion", "other", "taxable", false, false, false, "Check de minimis rules for monetized unused leave; default taxable."],
  ["SEPARATION", "Separation / retirement benefit", "other", "taxable", false, false, false, "Exempt only in qualifying cases (e.g. separation beyond the employee's control). Change treatment per case."],
  ["ADJ_EARN", "Payroll adjustment (earning)", "other", "taxable", true, false, false, "From approved payroll adjustments."],
  ["ADJ_EARN_NT", "Payroll adjustment (non-taxable)", "other", "non_taxable", false, false, false, "From approved payroll adjustments."],
  ["OTHER_EARN", "Other earnings", "other", "taxable", true, false, false, ""],
];
sql.push(
  "insert into earning_types (code, label, category, tax_treatment, include_in_sss, include_in_pagibig, include_in_13th, bir_treatment_note) values",
  earningTypes.map((e) => `  (${q(e[0])}, ${q(e[1])}, ${q(e[2])}, ${q(e[3])}, ${e[4]}, ${e[5]}, ${e[6]}, ${q(e[7])})`).join(",\n") + ";",
  ""
);

const P1006 = "Proclamation No. 1006, s. 2025";
const holidays: [string, string, string][] = [
  ["2026-01-01", "New Year's Day", "regular"],
  ["2026-02-17", "Chinese New Year", "special_non_working"],
  ["2026-02-25", "EDSA People Power Revolution Anniversary", "special_working"],
  ["2026-04-02", "Maundy Thursday", "regular"],
  ["2026-04-03", "Good Friday", "regular"],
  ["2026-04-04", "Black Saturday", "special_non_working"],
  ["2026-04-09", "Araw ng Kagitingan", "regular"],
  ["2026-05-01", "Labor Day", "regular"],
  ["2026-06-12", "Independence Day", "regular"],
  ["2026-08-21", "Ninoy Aquino Day", "special_non_working"],
  ["2026-08-31", "National Heroes Day", "regular"],
  ["2026-11-01", "All Saints' Day", "special_non_working"],
  ["2026-11-02", "All Souls' Day", "special_non_working"],
  ["2026-11-30", "Bonifacio Day", "regular"],
  ["2026-12-08", "Feast of the Immaculate Conception of Mary", "special_non_working"],
  ["2026-12-24", "Christmas Eve", "special_non_working"],
  ["2026-12-25", "Christmas Day", "regular"],
  ["2026-12-30", "Rizal Day", "regular"],
  ["2026-12-31", "Last Day of the Year", "special_non_working"],
];
sql.push(
  "-- Eid'l Fitr and Eid'l Adha are proclaimed separately each year; add them from their own proclamations.",
  "insert into holidays (holiday_date, name, holiday_type, source) values",
  holidays.map((h) => `  (${q(h[0])}, ${q(h[1])}, ${q(h[2])}, ${q(P1006)})`).join(",\n") + ";",
  ""
);

const WO = "Wage Order No. IVA-22 (2nd tranche)";
const SRC = "NWPC Region IV-A current daily minimum wage rates (nwpc.dole.gov.ph/region-iva)";
const wages: [string, string, number][] = [
  ["Component cities", "non_agriculture", 600],
  ["Component cities", "agriculture", 525],
  ["Component cities", "retail_service", 508],
  ["Reclassified 1st class municipalities", "non_agriculture", 550],
  ["Reclassified 1st class municipalities", "agriculture", 525],
  ["Reclassified 1st class municipalities", "retail_service", 508],
  ["2nd to 5th class municipalities", "non_agriculture", 525],
  ["2nd to 5th class municipalities", "agriculture", 508],
  ["2nd to 5th class municipalities", "retail_service", 508],
];
sql.push(
  "-- CALABARZON only. Rows for Extended Metropolitan Area / 1st class municipalities and for other regions",
  "-- must be added from the applicable NWPC wage order. Retail/service = establishments with ≤10 workers.",
  "insert into minimum_wage_rates (region, area_classification, sector, wage_order, effective_from, daily_rate, source) values",
  wages.map((w) => `  ('IV-A', ${q(w[0])}, ${q(w[1])}, ${q(WO)}, '2026-04-01', ${w[2]}, ${q(SRC)})`).join(",\n") + ";",
  "",
  "insert into departments (name) values ('Operations'), ('Sales'), ('Administration'), ('Warehouse');",
  "insert into positions (name) values ('Delivery Rider'), ('Driver'), ('Helper'), ('Showroom Staff'), ('Sales Agent'), ('Warehouse Staff'), ('Admin Staff'), ('Cashier');",
  "insert into branches (name, region) values ('Main', 'IV-A');",
  ""
);

const out = "supabase/migrations/20261002000300_seed_reference_data.sql";
writeFileSync(out, sql.join("\n"));
console.log("wrote", out);
